### PR TITLE
Function names

### PR DESCRIPTION
**Pull request by matthewecampbell**
I wanted to make sure the function names were clearer for the reader.  @msjennygiraffe  @neight-allen

### CODE REVIEW

**Comment by MsJennyGiraffe** [comment]
I personally don't understand why putting if in front makes it clearer. If should makes it sound very not English. I would either stick to the names you have, take out the should and just have if, or think of naming them to make them descriptive of what they do.

**Comment by matthewecampbell** [comment]
Cool, I like the advice.  I switched it to just ifx.   Thanks, @MsJennyGiraffe.

**Comment by MsJennyGiraffe** [comment]
Glad it was helpful. It makes more sense, to me at least. Keep it up, guys! 👍

**Review by neight-allen — COMMENTED** [review]
Yup, I remember complaining about this. I'm not sure what I think these methods should be called. It's something like `checkForMoveRightInputAndMoveRightIfAble`, which makes me think that this function is doing too much, or at least an arbitrary set of actions. I think the full refactor would be a set of functions like `checkMoveInput(value)`, `canMove(direction)` and `move(direction)`

**Pull request merged**
